URLS = [
    "https://www.apsit.edu.in/",
    "https://www.apsit.edu.in/about-us",
    "https://www.apsit.edu.in/permissions",
    "https://www.apsit.edu.in/apsit-nirf-data",
    "https://www.apsit.edu.in/nbaDCS",
    "https://www.apsit.edu.in/mandatory-disclosure-3",
    "https://www.apsit.edu.in/balance-sheet",
    "https://www.apsit.edu.in/governing-body-1",
    "https://www.apsit.edu.in/controller-examination",
    "https://www.apsit.edu.in/academic-council",
    "https://www.apsit.edu.in/departments",
    "https://www.apsit.edu.in/ug-courses",
    "https://www.apsit.edu.in/institute-calendar",
    "https://www.apsit.edu.in/library",
    "https://www.apsit.edu.in/admission-criteria",
    "https://www.apsit.edu.in/fee-structure-2025-26",
    "https://www.apsit.edu.in/admission-faqs",
    "https://www.apsit.edu.in/exam-notices",
    "https://www.apsit.edu.in/placement-records",
    "https://www.apsit.edu.in/tpo",
    "https://www.apsit.edu.in/student-council",
    "https://www.apsit.edu.in/apply",
    "https://www.apsit.edu.in/reach-us",

    # PDFs
    "https://www.apsit.edu.in/sites/default/files/2025-06/Institutional%20Development%20Plan%20-%20APSIT_0.pdf",
    "https://www.apsit.edu.in/sites/default/files/2025-12/FRA%20Proposal%2026-27.pdf",
    "https://www.apsit.edu.in/sites/default/files/2025-06/Brochure%202025-26%204mb.pdf",
]